version: '3' #docker-composeのバージョンを指定
services:
  book_db:
    image: mysql:5.7 #mysql5.7が準備されているimageを指定
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: book #rootのパスワード
      MYSQL_DATABASE: book #データベースの作成
    volumes:
      - "./mysql/init:/docker-entrypoint-initdb.d"
  gin_api:
    links:
      - book_db
    build: . #Dockerfileをビルド
    ports:
      - "8000:8000" #ポート8000番の開放
    entrypoint: sh /wait-for-mysql.sh book_db gin_api
